---
# tasks file for base
- name: Provisioning of VMs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-pip
    - curl
    - wget
    - sudo
    - net-tools
  become: yes
