---
# tasks file for nginx
- name: Install naked nginx
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
  become: yes
  when: ansible_os_family == "Debian" and ansible_distribution_version == "18.04"

- name: Allow firewall rules
  command: "ufw allow 'Nginx HTTP'"
  become: yes
  changed_when: false


